# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4b0a11d67841ce73ad64767ae334f8f6"
application_url = "https://7055-118-70-128-84.ngrok-free.app"
embedded = true
name = "remix-app"
handle = "remix-app-280"

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://7055-118-70-128-84.ngrok-free.app/auth/callback",
  "https://7055-118-70-128-84.ngrok-free.app/auth/shopify/callback",
  "https://7055-118-70-128-84.ngrok-free.app/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "tungnk-test-smart-forecast.myshopify.com"
automatically_update_urls_on_dev = true
